export enum BackgroundColor {
    Red = 'red',
    Pink = 'pink',
    Purple = 'purple',
    DeepPurple = 'deep-purple',
    Indigo = 'indigo',
    Blue = 'blue',
    LightBlue = 'light-blue',
    Cyan = 'cyan',
    Teal = 'teal',
    Green = 'green',
    LightGreen = 'light-green',
    Lime = 'lime',
    Yellow = 'yellow',
    Amber = 'amber',
    Orange = 'orange',
    DeepOrange = 'deep-orange',
    Brown = 'brown',
    Grey = 'grey',
    BlueGrey = 'blue-grey',
    Black = 'black',
    White = 'white'
}