export enum TextColor {
    Red = 'red-text',
    Pink = 'pink-text',
    Purple = 'purple-text',
    DeepPurple = 'deep-purple-text',
    Indigo = 'indigo-text',
    Blue = 'blue-text',
    LightBlue = 'light-blue-text',
    Cyan = 'cyan-text',
    Teal = 'teal-text',
    Green = 'green-text',
    LightGreen = 'light-green-text',
    Lime = 'lime-text',
    Yellow = 'yellow-text',
    Amber = 'amber-text',
    Orange = 'orange-text',
    DeepOrange = 'deep-orange-text',
    Brown = 'brown-text',
    Grey = 'grey-text',
    BlueGrey = 'blue-grey-text',
    Black = 'black-text',
    White = 'white-text',
    Default = ''
}
